### ISSUE TITLE
Faceted search does not work anymore

### ISSUE THREAD

**Issue by Jako** [Sterc/SimpleSearch#13]
I am not sure what is missing, but this does not work anymore:

https://docs.modx.com/extras/revo/simplesearch/simplesearch.simplesearch/simplesearch.faceted-search-through-posthooks

**Comment by Jako** [comment]
The faceted hook runs through, but the result is not displayed.

**Comment by sdrenth** [comment]
@Jako That's because the placeholder prefix has been changed to `simplesearch.`.

I've tested with the example as you provided and got it working with the following code:
```
[[!SimpleSearch? &toPlaceholder=`simplesearch.results` &postHooks=`PeopleFacetHook` &facetLimit=`5`]]

<h2>Search Results</h2>
[[!+simplesearch.results]]
 
<h2>People</h2>
[[!+simplesearch.people.results]]

```

**Comment by Jako** [comment]
Thanks, could you then update the docs, please?

**Comment by sdrenth** [comment]
@Jako I've added a comment in the readme and also updated the docs:
https://docs.modx.com/extras/revo/simplesearch/simplesearch.simplesearch

**Comment by Jako** [comment]
The wrong prefix is missing on the subpages: https://docs.modx.com/extras/revo/simplesearch/simplesearch.simplesearch/simplesearch.faceted-search-through-posthooks
