### ISSUE TITLE
Exclude tv fields?

### ISSUE THREAD

**Issue by aolko** [Sterc/SimpleSearch#14]
Is it possible to exclude specific tv's fields and how, i keep getting empty text results because it keeps searching tv fields i don't want it to search

**Comment by travisbotello** [comment]
This seems to be broken right now...

https://github.com/Sterc/SimpleSearch/pull/11

**Comment by sdrenth** [comment]
@aolko I think this is fixed in 2.1.0, can you confirm that this issue has been resolved?
