### ISSUE TITLE
includeTVList property not working

### ISSUE THREAD

**Issue by travisbotello** [Sterc/SimpleSearch#3]
I am using the `&includeTVList` to limit the TVs that are processed by SimpleSearch. However it seems to me that this setting isn't doing anything because I have access to all TVs in the `&tpl`, no matter if they are set in `&includeTVList` or not.

Using SimpleSearch 2.0.0 in MODx Revo 2.6.5

**Comment by travisbotello** [comment]
Created PR https://github.com/Sterc/SimpleSearch/pull/5

**Comment by MrRoco** [comment]
@travisbotello Your PR has been tested & merged.
Issue will be resolved by the next release.
