### ISSUE TITLE
currentPageTpl only working on first page

### ISSUE THREAD

**Issue by travisbotello** [Sterc/SimpleSearch#4]
After upgrading from 1.9.2 to 2.0.0 the pagination is no longer working. `&currentPageTpl` is only rendered on first page of results. When navigating to next page `&currentPageTpl` is not rendered and no active page is shown. All page numbers using the `&pageTpl` when offset is set in the URL. Also tried to use the snippet default properties without any luck. I assume this has to do with changing the `&offsetIndex` to `simplesearch_offset`.

Using SimpleSearch 2.0.0 in MODx Revo 2.6.5

**Comment by jonleverrier** [comment]
I'm able to reproduce the same problem as @travisbotello

**Comment by travisbotello** [comment]
Problem is caused by code cleanup https://github.com/Sterc/SimpleSearch/blob/9a2a63741eecd2161622a1adc0b373e405b75a68/core/components/simplesearch/model/simplesearch/simplesearch.class.php#L260

The condition to render `&currentPageTpl` is `false` because in

`if ($currentOffset === $pageArray['offset'])`

`$currentOffset` is of type `string` and `$pageArray['offset']` is of type `int`.

**Comment by travisbotello** [comment]
Created PR https://github.com/Sterc/SimpleSearch/pull/6

**Comment by MrRoco** [comment]
@travisbotello Your PR has been tested & merged.
Issue will be resolved by the next release.
