### ISSUE TITLE
Why did you not fork the original or modxcms repository?

### ISSUE THREAD

**Issue by Jako** [Sterc/SimpleSearch#8]

**Comment by gpsietzema** [comment]
We did, but not through github I guess.

**Comment by Jako** [comment]
Yes, and now the initial source of the repository is not detectable anymore.

**Comment by sdrenth** [comment]
@Jako @gpsietzema The repo is based on the latest simplesearch version which is https://github.com/modxcms/SimpleSearch. We noticed later on that the https://github.com/modxcms/SimpleSearch repo existed, so normally we would fork the repo.

**Comment by Jako** [comment]
Maybe you could rename your repository, fork the original repository and merge your changes into that fork.
