### ISSUE TITLE
Auto Suggestions

### ISSUE THREAD

**Issue by robliberty** [Sterc/SimpleSearch#9]
Can you provide a working example of the Auto Suggestion feature, I've followed the steps closely multiple times and still just get 'undefined' in the console log. Is the example jquery script non-functioning?

Please don't close this topic until it's bee answered. My previous "Issue" was closed a little early.

**Comment by sdrenth** [comment]
@robliberty I'm sorry we closed the issue too early. Hopefully this example will get it working for you!

```javascript
$.ajax({
    url         : '/assets/components/simplesearch/connector.php?action=web/autosuggestions&search=' + value,
    dataType    : 'JSON',
    complete    : function (result) {
        var suggestions = [];
        if (result.responseJSON.results.length) {
            $(result.responseJSON.results).each(function (idx, suggestion) {
                suggestions.push(
                    $('<li>', {
                        'html': suggestion,
                        'data-suggestion': suggestion
                    })
                );
            });
        }
    }
});
```

**Comment by sdrenth** [comment]
@robliberty Did you manage to get it working with the example provided?

**Comment by robliberty** [comment]
No. I just decided to write my own autosuggest feature, which works great for my needs.

**Comment by sdrenth** [comment]
@robliberty I'm sorry to hear that, but great that you found a working work-around.
